server:
  port: ${HOST_PORT:8091}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}

# Server Admin Client
  boot:
    admin:
      client:
        url: ${HOST_ADMIN_SERVER:http://localhost:8890}
        instance:
          management-base-url: http://localhost:${server.port}
        
# Server Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: ${HOST_EUREKA_SERVER:http://localhost:8889/eureka}

# Endpoints exposition
management:
  endpoints:
    web:
     exposure:
       include: "*"
     health:
       show-details: always
  endpoint:
    gateway:
      enabled: false
