server:
   port: ${HOST_PORT:8082}

# PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:db-reservation}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}

---
# Server Admin Client
spring:
  boot:
    admin:
      client:
        url: ${HOST_ADMIN_SERVER:http://localhost:8890}
        instance:
          management-base-url: http://localhost:${server.port}
        
# Server Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: ${HOST_EUREKA_SERVER:http://localhost:8889/eureka}

# Endpoints exposition
management:
  endpoints:
    web:
     exposure:
       include: "*"
     health:
       show-details: always
  endpoint:
    gateway:
      enabled: false

resilience4j:
  circuitbreaker:
    instances:
      event:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
