server:
   port: ${HOST_PORT:8086}

# Server Admin Client
spring:
  boot:
    admin:
      client:
        url: ${HOST_ADMIN_SERVER:http://localhost:8890}
        instance:
          management-base-url: http://localhost:${server.port}
        
# Server Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: ${HOST_EUREKA_SERVER:http://localhost:8889/eureka}

# Endpoints exposition
management:
  endpoints:
    web:
     exposure:
       include: "*"
     health:
       show-details: always
  endpoint:
    gateway:
      enabled: false

---
mongo:
  user: ${DB_USER:root}
  password: ${DB_PASS:secret}
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:27017}
  database: ${DB_DATABASE:project-163}
  ssl-enabled: false
  connection-timeout: 100000
  socket-timeout: 100000
