server:
  port: ${HOST_PORT:8891}

# Server Admin Client
spring:
  boot:
    admin:
      client:
        url: ${HOST_ADMIN_SERVER:http://localhost:8890}
        instance:
          management-base-url: http://localhost:${server.port}
        
# Server Registry Client
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: ${HOST_EUREKA_SERVER:http://localhost:8889/eureka}
  instance:
    prefer-ip-address: true

# Endpoints exposition
management:
  endpoints:
    web:
     exposure:
       include: "*"
     health:
       show-details: always
  endpoint:
    gateway:
      enabled: false

---
spring:
  cloud:
    gateway:
      routes:
        - id: service-security
          uri: lb://SERVICE-SECURITY
          predicates:
            - Path=/auth/**
        - id: service-reservation
          uri: lb://SERVICE-RESERVATION
          predicates:
            - Path=/reservation/**
          filters:
            - name: JwtAuthentication
            - name: CircuitBreaker
              args:
                name: serviceReservationCircuitBreaker
                fallbackUri: forward:/fallback/reservation
                secured: false
        - id: service-event
          uri: lb://SERVICE-EVENT
          predicates:
            - Path=/event/**
          filters:
            - name: JwtAuthentication
            - name: CircuitBreaker
              args:
                name: serviceEventCircuitBreaker
                fallbackUri: forward:/fallback/event
                secured: true
        - id: service-payment
          uri: lb://SERVICE-PAYMENT
          predicates:
            - Path=/payment/**
          filters:
            - name: JwtAuthentication
            - name: CircuitBreaker
              args:
                name: servicePaymentCircuitBreaker
                fallbackUri: forward:/fallback/payment
        - id: service-notification
          uri: lb://SERVICE-NOTIFICATION
          predicates:
            - Path=/notification/**
          filters:
            - name: JwtAuthentication
            - name: CircuitBreaker
              args:
                name: serviceNotificationCircuitBreaker
                fallbackUri: forward:/fallback/notification
        - id: service-cqrs
          uri: lb://SERVICE-CQRS
          predicates:
            - Path=/cqrs/**
          filters:
            - name: JwtAuthentication
            - name: CircuitBreaker
              args:
                name: serviceCqrsCircuitBreaker
                fallbackUri: forward:/fallback/cqrs
        - id: service-orchestrator
          uri: lb://SERVICE-ORCHESTRATOR
          predicates:
            - Path=/process-reservation/**
          filters:
            - name: JwtAuthentication
            - name: CircuitBreaker
              args:
                name: serviceOrchestratorCircuitBreaker
                fallbackUri: forward:/fallback/orchestrator

resilience4j:
  circuitbreaker:
    instances:
      serviceReservationCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
      serviceEventCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
      servicePaymentCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
      serviceNotificationCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
      serviceCqrsCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
      serviceOrchestratorCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED

