server:
  port: ${HOST_PORT:9091}

# Server Admin Client
spring:
  boot:
    admin:
      client:
        url: ${HOST_ADMIN_SERVER:http://localhost:9090}
        instance:
          management-base-url: http://localhost:${server.port}

# Server Registry Client
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: ${HOST_EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,refresh"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

---
spring:
  cloud:
    gateway:
      routes:
        - id: service-training
          uri: lb://SERVICE-TRAINING
          predicates:
            - Path=/training/**
          filters:
            - name: JwtAuthentication
        - id: service-search
          uri: lb://SERVICE-SEARCH
          predicates:
            - Path=/test/**
          filters:
              args:
                name: serviceSearchCircuitBreaker
                fallbackUri: forward:/fallback/search

resilience4j:
  circuitbreaker:
    instances:
      serviceSearchCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
        

application:
  security:
    secret: 31bebf8548614f31863834cee33f98e2
