server:
  port: ${HOST_PORT:9090}
        
# Server Registry Client
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: ${HOST_EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

spring:
  boot:
    admin:
      discovery:
        enabled: true
        converter:
          management-context-path: actuator
